### ISSUE TITLE
Problems running the lcd simulator

### ISSUE THREAD

**Issue by co-dan** [stevenvar/OMicroB#16]
It appears that the lcd simulator cannot find the `lcd_cgrom.txt` file.

Steps to reproduce:

1. Build and install OMicroB as described in the README.
2. Go to `tests/tuto_7_liquidcrystal/`.
3. Run `make simul`

Output:

```
.. < building stuff > ..
./lcdexample.elf ../../bin/omicrob_pin_simulator '../../bin/omicrob_lcd_16x2_simulator e=PIN12 rs=PIN11 rw=PIN10 d4=PIN9 d5=PIN8 d6=PIN7 d7=PIN6 16x2'
delay(1000)
delay(50)
start '../../bin/omicrob_lcd_16x2_simulator e=PIN12 rs=PIN11 rw=PIN10 d4=PIN9 d5=PIN8 d6=PIN7 d7=PIN6 16x2' (pid = 28659)
start '../../bin/omicrob_pin_simulator' (pid = 28658)
Fatal error: exception Sys_error("/home/dan/projects/avr/lib/omicrob/lcd_cgrom.txt: No such file or directory")
```

**Comment by stevenvar** [comment]
Ok I'm sorry I'll correct this ASAP. For the time being you can just create a blank lcd_cgrom.txt file in the right directory and it shouldn't be a problem.
