### ISSUE TITLE
Problem with .h file path when using installed version of omicrob

### ISSUE THREAD

**Issue by stevenvar** [stevenvar/OMicroB#9]

**Comment by bvaugon** [comment]
Ok, some files was not copied and some symbolic links was broken during installation.
Fixed.

**Comment by stevenvar** [comment]
Uh thanks but it's worse now on a mac :) 

ld: warning: directory not found for option '-L/usr/X11R6/lib'
ld: library not found for -lX11
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bvaugon** [comment]
Surprising, I just add cp commands for non-copied files.
Maybe this fix unlock build showing further problems on Mac...

**Comment by stevenvar** [comment]
Nevermind I think it might be a problem with my configuration because of an update of my operating system.... :)

**Comment by stevenvar** [comment]
Ok everything works nicely for me now!
Closed.
